### ISSUE TITLE
Add Release For Easier Deployment

### ISSUE THREAD

**Issue by Willy-Kimura** [JacksiroKe/mBible4PC#1]
Great app! Kindly add your builds/releases in the **Releases** section for easier end-user deployment.

**Comment by JacksiroKe** [comment]
Hey Willy thanks for the uchokozi from your end about my project. I saw your notification on my email app and for once thought am dreaming. Its rare to find people raising issues on my project. I only have them on php community projects where I have projects attracting global interests.

Am just getting started on this after dumping .net over Qt for cross platform stuff. This project is a clone my other project https://github.com/vSongBook/vSongBook4PC which having succeeded with Windows and working on the Linux version, Once am done I can call it a release and then come back to this project to implement the same here.

**Comment by Willy-Kimura** [comment]
Hi Jack,

Hahaha. How did you even know I'm Kenyan? That rarely happens... 😄 I mean rarely. I think you assumed eey... But hey, you caught me - ni uchokozi baba. Just saw your project and thought, this IS quite interesting... Your idea not only solves a problem but drew my interest as most Kenyans barely explore the Desktop Utilities space like I do. So I tested it and I must say it's working really well and is very much stable. Good job!

As for me, I'm an avid .NET developer with some decent web & API experience. And we'll, .NET (WinForms) is cross-platform now so I ain't giving up yet. There's still so much it offers developers from across the board.

Feel free to checkout my GitHub profile and see some of the stuff I've worked on.

Thanks for saying hi. And great job sir!

________________________________

**Comment by JacksiroKe** [comment]
Hey Willy,

Before I start to respond to someone I will go checking who they are. Like you I have seen your wordpress and medium blog as well as your twitter which definitely means I have gone through your GitHub and what I found summarizing your work is your buymecofee profile. I wish I could buy your coffee there 😄. I also know you work with Kim Too Flex at Bunifu. I do watch his videos on Youtube and since at work am a Desktop App developer using .net I use his videos to be creative too. If you check my profile https://github.com/JacksiroKe/AnisiControls I have some custom controls which I did put on Nuget.

By the way let me warn you you put something on github its open to all scavengers like myself. Even on stackoverflow when someone comments and answers me I simply go checking about them all over the net and that way I end up discovering and learning more about them. Like you I now know you more than you know me. So you dont need to invite me to see what is on your github I already downloaded some of them and am into testing what you got there.

Awesome!
